.travis.yml
Create merge request for Dumitru
=> Webservice travis ci

.travis.yml, webservice/Procfile, webservice/pom.xml, webservice/src/main/java/HelloWorldService.java
4 deployment options were added. (check the links in planning docs)
asepartback-dev got an application error right now, since the pom.xml and the Procfile was written for Davids code on initDB Branch (and not for the HelloWorldService code which is still on my branch)
=> Deployment

webservice/src/main/java/de/fau/cs/osr/amos/asepart/WebService.java
port binding needed for deployment
=> Readd code lost during merging

admin-web-app/package-lock.json, admin-web-app/package.json, admin-web-app/src/components/Login/login.js, admin-web-app/src/components/Project/ProjectButton.js, admin-web-app/src/components/Project/ProjectList.js, admin-web-app/src/components/ProjectList.js, admin-web-app/src/index.js
project list is currently the default side
=> 30 list projects

webservice/src/main/java/de/fau/cs/osr/amos/asepart/Database.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/WebService.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/entities/Message.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/relationships/ProjectTicket.java, webservice/src/test/java/de/fau/cs/osr/amos/asepart/WebServiceTest.java, webservice/webservice-api.txt
Implemented ticket chat functionality. Also fixed some of the consistency problems with the tickets (#31).
=> Ticket chat (Backend)

webservice/src/main/java/de/fau/cs/osr/amos/asepart/Database.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/WebService.java, webservice/webservice-api.txt
REST calls for Mark and Tanjas tasks
=> new rest calls: delete user and get ticket

user-app/App.js, user-app/src/components/Chat/messages.js, user-app/src/components/Login/Design.js, user-app/src/components/Projects/ticketView.js
I added the detailed ticket view and changed the navigation flow as you can now reach the chat via the detailed ticket view.
=> added detailed ticket view with the description and navigation to chat

admin-web-app/src/components/Project/TicketDetail.js
Chat as link
Description as last item
=> 72 fix ticket detail view

admin-web-app/src/components/Chat/TicketChat.js, admin-web-app/src/components/Chat/TicketChatButton.js, admin-web-app/src/components/Login/login.js, admin-web-app/src/components/Project/ProjectList.js, admin-web-app/src/components/Project/TicketCreate.js, admin-web-app/src/components/Project/TicketDetail.js, admin-web-app/src/components/Project/TicketList.js, admin-web-app/src/components/Project/UpdateTicketButton.js, admin-web-app/src/components/Project/UserList.js, admin-web-app/src/index.js
Updated the chat url and buttons
=> 60 admin web app bookmarks

admin-web-app/src/components/Chat/TicketChat.js, user-app/src/components/Chat/messages.js, user-app/src/components/Login/Design.js
when sending to database: a timestamp is added to every message at the start - resulting in "[FRI JUN 08 2018, 20:02:02]: message"
while rendering the chat: the date is filtered out and all messages during one day are listed under that date without repeating the date for every message
the chat is now inside a scrollview - guaranteeing the textinput and the send button to be always at the bottom of the screen
merged textInput and send button into one row (userapp only) - saving screen estate 
a rendered message looks like: 
[00:00:00] user: message
=> 82 chat time

admin-web-app/src/components/Project/TicketList.js
Not yet tested due to broken back-end…
=> Add statistic

user-app/src/components/Login/Design.js, user-app/src/components/Projects/projectInfo.js
added color highlighting for ticket boxes according to ticket status and improved UI
=> 94 bugfix ticket list ui app

admin-web-app/src/components/Chat/ChatMessage.js, admin-web-app/src/components/Chat/TicketChat.js
Please review 1708d30 for correctness and completeness.
Line [192](https://github.com/asepart/amosss182/blob/1708d30744815bb55dc3ba3d5b2ad97b31921291/admin-web-app/src/components/Chat/TicketChat.js#L192) is already removed.
=> 00 create chat component admin

.codecov.yml, .travis.yml
check travis build history
build time is around 5min
=> Travis runtime

postgres/schema.sql, webservice/pom.xml, webservice/src/main/java/de/fau/cs/osr/amos/asepart/DatabaseClient.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/FileStorageClient.java, webservice/src/main/java/de/fau/cs/osr/amos/asepart/WebService.java, webservice/src/test/java/de/fau/cs/osr/amos/asepart/WebServiceTest.java, webservice/webservice-api.txt
Previews for images and video. Also includes the change to mark projects as finished.
=> Filepreview

user-app/src/components/Login/Design.js, user-app/src/components/Projects/keyValid.js
fixed the status 204 handling which caused an error. 
Also added some margin to the ticket boxes since it was a looking off a little bit
=> 99 bug fix ticket view

admin-web-app/src/components/Project/UpdateProjectButton.js
Backend does not support this function yet. Do not hesitate to keep the PR open until then.
=> Implemented finished checkbox

user-app/src/components/Projects/projectList.js, user-app/src/components/Projects/projectListTicketList.js
bug fix for not showing projects that are already finished
bug fix for leaving the project when accessing the tickets view from the project list button
=> 128 bug fix remove finished projects

user-app/App.js, user-app/src/components/Chat/messages.js, user-app/src/components/Login/Design.js, user-app/src/components/Projects/projectList.js, user-app/src/components/Projects/projectListTicketList.js, user-app/src/components/Projects/ticketView.js, user-app/src/components/Tickets/ticketProcessed.js
- added icon for user update in header 
- made some small changes in design
=> 0 user app design improvements

admin-web-app/src/components/Chat/TicketChat.js
=> Remove amount of messages on reload button

user-app/src/components/Chat/files.js, user-app/src/components/Login/auth.js, user-app/src/components/MediaSupport/cameraRollPicker.js
what works:
webapp:
- pictures, videos upload
userapp ios
- all image extensions
- only mov support
userapp android
- only jpg support
- only mp4 support
=> 127 video encoding
